server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_pass http://auth-service:8081/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /events/ {
        proxy_pass http://event-service:8082/events/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}