apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gigspot-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gigspot-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: gigspot-pod-reader
  apiGroup: rbac.authorization.k8s.io
